export const TableData = [
    {
      id: Math.random().toString(4),
      invoiceName: "Invoice #01-Dec 2022",
      balance: "paid",
      billDate: "Dec 1, 2023",
      amount: "10.00",
      plan: "Basic",
      users: "10",
    },
    {
      id: Math.random().toString(4),
      invoiceName: "Invoice #02-Dec 2022",
      balance: "unpaid",
      billDate: "Dec 2, 2023",
      amount: "20.00",
      plan: "Premium",
      users: "20",
    },
    {
      id: Math.random().toString(4),
      invoiceName: "Invoice #03-Dec 2022",
      balance: "paid",
      billDate: "Dec 3, 2023",
      amount: "15.00",
      plan: "Basic",
      users: "5",
    },
    {
      id: Math.random().toString(4),
      invoiceName: "Invoice #04-Dec 2022",
      balance: "unpaid",
      billDate: "Dec 4, 2023",
      amount: "30.00",
      plan: "Premium",
      users: "15",
    },
    {
      id: Math.random().toString(4),
      invoiceName: "Invoice #05-Dec 2022",
      balance: "paid",
      billDate: "Dec 5, 2023",
      amount: "25.00",
      plan: "Basic",
      users: "8",
    },
  ];
  